name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        event-name: [push]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        make talib_nix
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Install system dependencies
      run: |
        make talib_darwin
      if: ${{ matrix.os == 'macos-latest' }}

    - name: Install system dependencies
      run: |
        make talib_windows_py37
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == 3.7 }}

    - name: Install system dependencies
      run: |
        make talib_windows_py38
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == 3.8 }}

    - name: Install system dependencies
      run: |
        make talib_windows_py39
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == 3.9 }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
        python -m pip install -e .[dev]

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make tests
      if: ${{ github.event_name == matrix.event-name || matrix.os == 'ubuntu-latest' }}

    - name: Twine check
      run: |
        make dist

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: python_junit.xml
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: python_junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload coverage
      uses: codecov/codecov-action@v4
